// libs/react-components/src/tedi/components/base/typography/text/text.tsx
import cn from 'classnames';

import { BreakpointSupport, useBreakpointProps } from '../../../../helpers';
import type { HeadingLevel } from '../heading/heading';

export type HeadingModifiers = `h${HeadingLevel}`;

export type TextModifiers =
  | HeadingModifiers
  | 'normal'
  | 'small'
  | 'bold'
  | 'thin'
  | 'italic'
  | 'center'
  | 'left'
  | 'right'
  | 'nowrap'
  | 'break-all'
  | 'break-word'
  | 'break-spaces'
  | 'uppercase'
  | 'lowercase'
  | 'capitalize'
  | 'capitalize-first'
  | 'inline-block'
  | 'inline'
  | 'line-normal'
  | 'line-condensed'
  | 'subtitle';

export type TextColor =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'white'
  | 'disabled'
  | 'brand'
  | 'success'
  | 'warning'
  | 'danger'
  | 'info'
  | 'neutral';

export type TextElement = 'div' | 'p' | 'span' | 'li' | 'label' | HeadingModifiers;

type TextBreakpointProps = {
  /**
   * Additional class
   */
  className?: string;
  /**
   * Base element
   * @default p
   */
  element?: TextElement;
  /**
   * Single or multiple modifiers to change the text behavior
   */
  modifiers?: TextModifiers[] | TextModifiers;
  /**
   * Color of the text
   * Use 'success', 'important' or 'warning' with caution, usually they should not be in application UI
   * @default primary
   */
  color?: TextColor;
};

export interface TextProps extends BreakpointSupport<TextBreakpointProps> {
  /**
   * Children of the text
   */
  children: React.ReactNode;
  /**
   * ID attribute
   */
  id?: string;
  /**
   * Allows to focus the element
   */
  tabIndex?: number;
}

const isHeadingModifier = (modifier: TextModifiers): modifier is HeadingModifiers => {
  return /^h[1-6]$/.test(modifier);
};

export const Text = (props: TextProps): JSX.Element => {
  const { getCurrentBreakpointProps } = useBreakpointProps();
  const {
    children,
    className,
    tabIndex = props.id ? -1 : undefined,
    element: Element = 'p',
    modifiers,
    color,
    ...rest
  } = getCurrentBreakpointProps<TextProps>(props);

  const modifiersArray = typeof modifiers === 'string' ? [modifiers] : modifiers;

  const BEM = cn(
    className,
    modifiersArray?.map((modifier) => (isHeadingModifier(modifier) ? `tedi-text--${modifier}` : `text-${modifier}`)),
    { [`tedi-text--${color}`]: color }
  );

  return (
    <Element className={BEM} {...rest} tabIndex={tabIndex}>
      {children}
    </Element>
  );
};

// libs/angular-components/src/tedi/components/base/typography/text/text.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  InputSignal,
} from "@angular/core";
import {
  HeadingModifiers,
  isHeadingModifier,
} from "../heading/heading.component";

export type TextModifiers =
  | HeadingModifiers
  | "normal"
  | "small"
  | "bold"
  | "thin"
  | "italic"
  | "center"
  | "left"
  | "right"
  | "nowrap"
  | "break-all"
  | "break-word"
  | "break-spaces"
  | "uppercase"
  | "lowercase"
  | "capitalize"
  | "capitalize-first"
  | "inline-block"
  | "inline"
  | "line-normal"
  | "line-condensed"
  | "subtitle";

export type TextColor =
  | "primary"
  | "secondary"
  | "tertiary"
  | "white"
  | "disabled"
  | "brand"
  | "success"
  | "warning"
  | "danger"
  | "info"
  | "neutral";

export type TextElement =
  | "div"
  | "p"
  | "span"
  | "li"
  | "label"
  | HeadingModifiers;

export type TextProps = {
  /**
   * Additional class
   */
  class: InputSignal<string | undefined>;
  /**
   * ID attribute
   */
  id: InputSignal<string | undefined>;
  /**
   * Allows to focus the element
   */
  tabIndex: InputSignal<number | undefined>;
  /**
   * Base element
   * @default p
   */
  element: InputSignal<TextElement | undefined>;
  /**
   * Single or multiple modifiers to change the text behavior
   */
  modifiers: InputSignal<TextModifiers[] | TextModifiers | undefined>;
  /**
   * Color of the text
   * Use 'success', 'important' or 'warning' with caution, usually they should not be in application UI
   * @default primary
   */
  color: InputSignal<TextColor | undefined>;
};

@Component({
  selector: "tedi-text",
  templateUrl: "./text.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TextComponent implements TextProps {
  class = input<string | undefined>(undefined);
  id = input<string | undefined>(undefined);
  tabIndex = input<number | undefined>(undefined);
  element = input<TextElement | undefined>("p");
  modifiers = input<TextModifiers[] | TextModifiers | undefined>(undefined);
  color = input<TextColor | undefined>("primary");

  classes = computed(() => {
    const modifiersValue = this.modifiers();
    const modifierClasses = Array.isArray(modifiersValue)
      ? modifiersValue
      : modifiersValue
        ? [modifiersValue]
        : [];

    return [
      this.class(),
      ...modifierClasses.map((modifier) =>
        isHeadingModifier(modifier)
          ? `tedi-text--${modifier}`
          : `text-${modifier}`,
      ),
      this.color() ? `tedi-text--${this.color()}` : "",
    ]
      .filter(Boolean)
      .join(" ");
  });
}

@switch (element()) {
  @case ("div") {
    <div [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </div>
  }

  @case ("p") {
    <p [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </p>
  }

  @case ("span") {
    <span [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </span>
  }

  @case ("li") {
    <li [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </li>
  }

  @case ("label") {
    <label [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </label>
  }

  @case ("h1") {
    <h1 [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </h1>
  }

  @case ("h2") {
    <h2 [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </h2>
  }

  @case ("h3") {
    <h3 [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </h3>
  }

  @case ("h4") {
    <h4 [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </h4>
  }

  @case ("h5") {
    <h5 [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </h5>
  }

  @case ("h6") {
    <h6 [class]="classes()" [attr.id]="id()" [attr.tabindex]="tabIndex()">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </h6>
  }
}

<ng-template #content>
  <ng-content></ng-content>
</ng-template>
