// libs/angular-components/src/tedi/components/typography/text/text.component.ts
import { Component, Input } from "@angular/core";
import { HeadingModifiers } from "../heading/heading.component";

export type TextModifiers =
  | HeadingModifiers
  | "normal"
  | "small"
  | "bold"
  | "thin"
  | "italic"
  | "center"
  | "left"
  | "right"
  | "nowrap"
  | "break-all"
  | "break-word"
  | "break-spaces"
  | "uppercase"
  | "lowercase"
  | "capitalize"
  | "capitalize-first"
  | "inline-block"
  | "inline"
  | "line-normal"
  | "line-condensed"
  | "subtitle";

export type TextColor =
  | "primary"
  | "secondary"
  | "tertiary"
  | "white"
  | "disabled"
  | "brand"
  | "success"
  | "warning"
  | "danger"
  | "info"
  | "neutral";

export type TextElement =
  | "div"
  | "p"
  | "span"
  | "li"
  | "label"
  | HeadingModifiers;

export type TextProps = {
  /**
   * Additional class
   */
  class?: string;
  /**
   * ID attribute
   */
  id?: string;
  /**
   * Allows to focus the element
   */
  tabIndex?: number;
  /**
   * Base element
   * @default p
   */
  element?: TextElement;
  /**
   * Single or multiple modifiers to change the text behavior
   */
  modifiers?: TextModifiers[] | TextModifiers;
  /**
   * Color of the text
   * Use 'success', 'important' or 'warning' with caution, usually they should not be in application UI
   * @default primary
   */
  color?: TextColor;
};

@Component({
  selector: "tedi-text",
  templateUrl: "./text.component.html",
})
export class TextComponent implements TextProps {
  @Input() class?: string;
  @Input() id?: string;
  @Input() tabIndex?: number;
  @Input() element?: TextElement = "p";
  @Input() modifiers?: TextModifiers[] | TextModifiers;
  @Input() color?: TextColor = "primary";

  private isHeadingModifier(modifier: string): boolean {
    return /^h[1-6]$/.test(modifier);
  }

  get classes(): string {
    const modifierClasses = Array.isArray(this.modifiers)
      ? this.modifiers
      : this.modifiers
        ? [this.modifiers]
        : [];

    return [
      this.class,
      ...modifierClasses.map((modifier) =>
        this.isHeadingModifier(modifier)
          ? `tedi-text--${modifier}`
          : `text-${modifier}`,
      ),
      this.color ? `tedi-text--${this.color}` : "",
    ]
      .filter(Boolean)
      .join(" ");
  }
}

<ng-container [ngSwitch]="element">
  <div
    *ngSwitchCase="'div'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </div>
  <p
    *ngSwitchCase="'p'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </p>
  <span
    *ngSwitchCase="'span'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </span>
  <li
    *ngSwitchCase="'li'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </li>
  <label
    *ngSwitchCase="'label'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </label>
  <h1
    *ngSwitchCase="'h1'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h1>
  <h2
    *ngSwitchCase="'h2'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h2>
  <h3
    *ngSwitchCase="'h3'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h3>
  <h4
    *ngSwitchCase="'h4'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h4>
  <h5
    *ngSwitchCase="'h5'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h5>
  <h6
    *ngSwitchCase="'h6'"
    [class]="classes"
    [attr.id]="id"
    [attr.tabindex]="tabIndex"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h6>
</ng-container>

<ng-template #content>
  <ng-content></ng-content>
</ng-template>

// libs/react-components/src/tedi/components/typography/text/text.tsx
import cn from 'classnames';

import { BreakpointSupport, useBreakpointProps } from '../../../helpers';
import type { HeadingLevel } from '../heading/heading';

export type HeadingModifiers = `h${HeadingLevel}`;

export type TextModifiers =
  | HeadingModifiers
  | 'normal'
  | 'small'
  | 'bold'
  | 'thin'
  | 'italic'
  | 'center'
  | 'left'
  | 'right'
  | 'nowrap'
  | 'break-all'
  | 'break-word'
  | 'break-spaces'
  | 'uppercase'
  | 'lowercase'
  | 'capitalize'
  | 'capitalize-first'
  | 'inline-block'
  | 'inline'
  | 'line-normal'
  | 'line-condensed'
  | 'subtitle';

export type TextColor =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'white'
  | 'disabled'
  | 'brand'
  | 'success'
  | 'warning'
  | 'danger'
  | 'info'
  | 'neutral';

export type TextElement = 'div' | 'p' | 'span' | 'li' | 'label' | HeadingModifiers;

type TextBreakpointProps = {
  /**
   * Additional class
   */
  className?: string;
  /**
   * Base element
   * @default p
   */
  element?: TextElement;
  /**
   * Single or multiple modifiers to change the text behavior
   */
  modifiers?: TextModifiers[] | TextModifiers;
  /**
   * Color of the text
   * Use 'success', 'important' or 'warning' with caution, usually they should not be in application UI
   * @default primary
   */
  color?: TextColor;
};

export interface TextProps extends BreakpointSupport<TextBreakpointProps> {
  /**
   * Children of the text
   */
  children: React.ReactNode;
  /**
   * ID attribute
   */
  id?: string;
  /**
   * Allows to focus the element
   */
  tabIndex?: number;
}

const isHeading = (value: TextElement | TextModifiers): value is HeadingModifiers => {
  return /^h[1-6]$/.test(value);
};

export const Text = (props: TextProps): JSX.Element => {
  const { getCurrentBreakpointProps } = useBreakpointProps();
  const {
    children,
    className,
    tabIndex = props.id ? -1 : undefined,
    element: Element = 'p',
    modifiers,
    color,
    ...rest
  } = getCurrentBreakpointProps<TextProps>(props);

  const modifiersArray = typeof modifiers === 'string' ? [modifiers] : modifiers;
  const hasHeadingModifier = modifiersArray?.some(isHeading);
  const headingClass = isHeading(Element) && !hasHeadingModifier ? `tedi-text--${Element}` : null;

  const BEM = cn(
    className,
    headingClass,
    modifiersArray?.map((modifier) => (isHeading(modifier) ? `tedi-text--${modifier}` : `text-${modifier}`)),
    { [`tedi-text--${color}`]: color }
  );

  return (
    <Element className={BEM} {...rest} tabIndex={tabIndex}>
      {children}
    </Element>
  );
};
