// libs/angular-components/src/tedi/components/typography/heading/heading.component.ts
import { Component, Input } from "@angular/core";
import { TextColor, TextModifiers, TextProps } from "../text/text.component";

export type HeadingLevel = 1 | 2 | 3 | 4 | 5 | 6;
export type HeadingModifiers = `h${HeadingLevel}`;

export type HeadingProps = Omit<TextProps, "element"> & {
  /**
   * Semantic heading tag
   * h1-h6 are allowed values
   * @default h1
   */
  element?: HeadingModifiers;
};

@Component({
  selector: "tedi-heading",
  templateUrl: "./heading.component.html",
})
export class HeadingComponent implements HeadingProps {
  @Input() class?: string;
  @Input() id?: string;
  @Input() tabIndex?: number;
  @Input() element?: HeadingModifiers = "h1";
  @Input() modifiers?: TextModifiers[] | TextModifiers;
  @Input() color?: TextColor = "primary";

  get classes(): string {
    const modifierClasses = Array.isArray(this.modifiers)
      ? this.modifiers
      : this.modifiers
        ? [this.modifiers]
        : [];
    return [this.class, ...modifierClasses, this.color]
      .filter(Boolean)
      .join(" ");
  }
}

<ng-container [ngSwitch]="element()">
  <h1
    *ngSwitchCase="'h1'"
    [class]="classes()"
    [attr.id]="id()"
    [attr.tabindex]="tabIndex()"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h1>
  <h2
    *ngSwitchCase="'h2'"
    [class]="classes()"
    [attr.id]="id()"
    [attr.tabindex]="tabIndex()"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h2>
  <h3
    *ngSwitchCase="'h3'"
    [class]="classes()"
    [attr.id]="id()"
    [attr.tabindex]="tabIndex()"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h3>
  <h4
    *ngSwitchCase="'h4'"
    [class]="classes()"
    [attr.id]="id()"
    [attr.tabindex]="tabIndex()"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h4>
  <h5
    *ngSwitchCase="'h5'"
    [class]="classes()"
    [attr.id]="id()"
    [attr.tabindex]="tabIndex()"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h5>
  <h6
    *ngSwitchCase="'h6'"
    [class]="classes()"
    [attr.id]="id()"
    [attr.tabindex]="tabIndex()"
  >
    <ng-container [ngTemplateOutlet]="content"></ng-container>
  </h6>
</ng-container>

<ng-template #content>
  <ng-content></ng-content>
</ng-template>

// libs/react-components/tedi/src/components/typography/heading/heading.tsx
import { HeadingModifiers, Text, TextProps } from '../text/text';

export type HeadingLevel = 1 | 2 | 3 | 4 | 5 | 6;

export type HeadingProps = Omit<TextProps, 'element'> & {
  /**
   * Semantic heading tag
   * h1-h6 are allowed values
   * @default h1
   */
  element?: Extract<TextProps['element'], HeadingModifiers>;
};

export const Heading = (props: HeadingProps) => {
  const { children, element = 'h1', ...rest } = props;

  return (
    <Text element={element} {...rest}>
      {children}
    </Text>
  );
};
