// libs/react-components/src/tedi/components/notifications/alert/alert.tsx
import cn from 'classnames';
import React from 'react';

import { BreakpointSupport, useBreakpointProps, useIsMounted } from '../../../helpers';
import { Icon, IconWithoutBackgroundProps } from '../../base/icon/icon';
import { Heading } from '../../base/typography/heading/heading';
import { ClosingButton } from '../../buttons/closing-button/closing-button';
import { Col, Row } from '../../layout/grid';
import { VerticalSpacing } from '../../layout/vertical-spacing';
import styles from './alert.module.scss';

export type AlertType = 'info' | 'success' | 'warning' | 'danger';

type AlertBreakpointProps = {
  /**
   * Additional CSS class names to apply to the alert for custom styling.
   * Allows combining multiple styles or adding external CSS classes.
   */
  className?: string;
  /**
   * Indicates that the alert is intended to span the full width of the page,
   * typically for critical or prominent messages.
   * @default false
   */
  isGlobal?: boolean;
  /**
   * Removes the side borders from the alert for a cleaner appearance.
   * This also sets the border radius to 0.
   * @default false
   */
  noSideBorders?: boolean;
};

export interface AlertProps extends BreakpointSupport<AlertBreakpointProps> {
  /**
   * The primary content displayed within the alert. This can include text, links, or other elements.
   */
  children?: React.ReactNode;
  /**
   * An optional title for the alert, typically used to summarize the message's purpose.
   * If provided, it appears prominently at the top of the alert.
   */
  title?: React.ReactNode;
  /**
   * Defines the visual and contextual type of the alert. This determines the icon, color, and
   * overall style, making it clear whether the alert is informational, a success message,
   * a warning, or an error.
   * @default info
   */
  type?: AlertType;
  /**
   * Specifies an optional icon to display in the alert, providing quick visual context.
   * Can be a string (icon name) or an object with additional `IconProps` to further customize the icon.
   */
  icon?: string | IconWithoutBackgroundProps;
  /**
   * Callback function triggered when the close button is clicked.
   * Adding this handler renders a close button in the alert.
   * Useful for dismissible alerts.
   */
  onClose?: () => void;
  /**
   * The ARIA role of the alert, informing screen readers about the alert's purpose.
   * Options:
   * - 'alert': For high-priority messages that demand immediate attention.
   * - 'status': For less urgent messages providing feedback or updates.
   * - 'none': Used when no ARIA role is needed.
   * @default alert
   */
  role?: 'alert' | 'status' | 'none';
}

export const Alert = (props: AlertProps): JSX.Element | null => {
  const { getCurrentBreakpointProps } = useBreakpointProps();
  const {
    children,
    role = 'alert',
    title,
    className,
    type = 'info',
    icon,
    onClose,
    isGlobal = false,
    noSideBorders = false,
    ...rest
  } = getCurrentBreakpointProps<AlertProps>(props);

  const alertBEM = cn(
    styles['tedi-alert'],
    styles[`tedi-alert--${type}`],
    {
      [styles['tedi-alert--global']]: isGlobal,
      [styles['tedi-alert--no-side-borders']]: noSideBorders,
    },
    className
  );

  const isMounted = useIsMounted();

  const getIcon = (icon: string | IconWithoutBackgroundProps) => {
    const defaultIconProps: Partial<IconWithoutBackgroundProps> = { size: 18 };
    const iconProps: IconWithoutBackgroundProps =
      typeof icon === 'string' ? { ...defaultIconProps, name: icon } : { ...defaultIconProps, ...icon };

    return (
      <div className={styles['tedi-alert__icon']}>
        <Icon {...iconProps} />
      </div>
    );
  };

  const ariaLive = role === 'alert' ? 'assertive' : role === 'status' ? 'polite' : 'off';

  return isMounted ? (
    <div
      role={role}
      data-name="alert"
      aria-live={ariaLive}
      aria-label={title ? `${type} alert: ${title}` : `${type} alert`}
      {...rest}
      className={alertBEM}
    >
      <VerticalSpacing size={0.25}>
        <Row gutterX={2} alignItems={title ? 'center' : 'start'}>
          <Col grow={1} className={styles['tedi-alert__content']}>
            {icon && getIcon(icon)}
            <div className="tedi-alert__content-wrapper">
              {title ? <Heading element="h5">{title}</Heading> : children}
            </div>
          </Col>
          {onClose && (
            <Col width="auto">
              <ClosingButton onClick={onClose} aria-label="Close alert" />
            </Col>
          )}
        </Row>
        {title && children && <div className="tedi-alert__content-wrapper">{children}</div>}
      </VerticalSpacing>
    </div>
  ) : null;
};

export default Alert;

// libs/angular-components/tedi/components/notifications/alert/alert.component.ts
import {
  Component,
  computed,
  ElementRef,
  inject,
  input,
  Renderer2,
  ViewChild,
  AfterViewInit,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { IconComponent } from "../../base/icon/icon.component";
import { ClosingButtonComponent } from "../../../../community/components/buttons/closing-button/closing-button.component";

export type AlertRole = "alert" | "status" | "none";
export type AlertType = "info" | "success" | "warning" | "danger";
export type AlertTitleType =
  | "h1"
  | "h2"
  | "h3"
  | "h4"
  | "h5"
  | "h6"
  | "div"
  | "strong";
export type AlertVariant = "default" | "global" | "noSideBorders";

@Component({
  standalone: true,
  selector: "tedi-alert",
  imports: [CommonModule, IconComponent, ClosingButtonComponent],
  templateUrl: "./alert.component.html",
  styleUrls: ["./alert.component.scss"],
})
export class AlertComponent implements AfterViewInit {
  /**
   * An optional title for the alert, typically used to summarize the message's purpose.
   * If provided, it appears prominently at the top of the alert.
   */
  title = input<string>();
  /**
   * Defines the visual and contextual type of the alert. This determines the icon, color, and
   * overall style, making it clear whether the alert is informational, a success message,
   * a warning, or an error.
   * @default info
   */
  type = input<AlertType>("info");
  /**
   * Specifies an optional icon to display in the alert, providing quick visual context.
   * Can be a string (icon name) or an object with additional `IconProps` to further customize the icon.
   */
  icon = input<string>("");
  /**
   * If true, a close button will be displayed.
   * @default false
   */
  showClose = input<boolean>(false);
  /**
   * The ARIA role of the alert, informing screen readers about the alert's purpose.
   * Options:
   * - 'alert': For high-priority messages that demand immediate attention.
   * - 'status': For less urgent messages providing feedback or updates.
   * - 'none': Used when no ARIA role is needed.
   * @default alert
   */
  role = input<AlertRole>("alert");
  /**
   * Indicates that the alert is intended to span the full width of the page,
   * typically for critical or prominent messages.
   * @default false
   */
  isGlobal = input<boolean>();
  /**
   * Removes the side borders from the alert for a cleaner appearance.
   * This also sets the border radius to 0.
   * @default false
   */
  noSideBorders = input<boolean>();

  /**
   * Variant for the alert, which can be used to apply specific styles.
   * For example, 'global' for full-width alerts or 'noSideBorders' for alerts without side borders.
   */
  variant = input<AlertVariant>("default");

  /**
   * The HTML tag to be used for the alert title.
   * @default h2
   */
  titleElement = input<AlertTitleType>("h2");

  @ViewChild("alertTitle", { static: true })
  headingAnchor!: ElementRef<HTMLElement>;
  renderer = inject(Renderer2);

  ngAfterViewInit() {
    if (this.title()) {
      const headingTag = this.titleElement();
      const headingElement = this.renderer.createElement(headingTag);

      this.renderer.setAttribute(headingElement, "tedi-text", "");
      this.renderer.addClass(headingElement, "tedi-alert__title__text");

      const text = this.renderer.createText(this.title()!);

      this.renderer.appendChild(headingElement, text);
      this.renderer.appendChild(
        this.headingAnchor.nativeElement,
        headingElement,
      );
    }
  }

  getAriaLive = computed(() => {
    switch (this.role()) {
      case "alert":
        return "assertive";
      case "status":
        return "polite";
      case "none":
        return "off";
      default:
        return "off";
    }
  });

  getAriaLabel = computed(() => {
    if (this.title()) {
      return `${this.type()} alert: ${this.title()}`;
    }
    return `${this.type()} alert`;
  });

  getRole = computed(() => {
    return this.role() === "none" ? null : this.role();
  });

  getClasses = computed(() => {
    return {
      "tedi-alert": true,
      [`tedi-alert--${this.type()}`]: !!this.type(),
      "tedi-alert--global": this.variant() === "global",
      "tedi-alert--no-side-borders": this.variant() === "noSideBorders",
    };
  });
}

<div
  [attr.aria-live]="getAriaLive()"
  [attr.aria-label]="getAriaLabel()"
  [class]="getClasses()"
  [attr.role]="getRole()"
>
  <div
    class="tedi-alert__container"
    [class.tedi-alert__title-layout]="title()"
    [class.tedi-alert__icon-layout]="icon()"
  >
    <tedi-icon *ngIf="icon()" class="tedi-alert__icon" [name]="icon()" />
    <div class="tedi-alert__content">
      <ng-content />
    </div>
    <button
      tedi-closing-button
      *ngIf="showClose()"
      class="tedi-alert__close"
    ></button>
    <div class="tedi-alert__title__container" #alertTitle></div>
  </div>
</div>
