// libs/angular-components/community/components/text-group/text-group.component.ts
import { Component, computed, input } from "@angular/core";
import type { InputsWithSignals } from "@tehik-ee/tedi-angular/tedi";

type TextGroupType = "vertical" | "horizontal";

export type TextGroup = {
  /**
   * Type of text group layout
   * @default 'horizontal'
   */
  type: TextGroupType;
  /**
   * Width for the label (e.g., '200px', '30%', etc.)
   * @default 'auto'
   */
  labelWidth: string;
  /**
   * Label for the text group
   */
  label?: string;
  /**
   * Value displayed alongside the label
   */
  value?: string;
};

@Component({
  standalone: true,
  selector: "tedi-text-group",
  imports: [],
  templateUrl: "./text-group.component.html",
  styleUrl: "./text-group.component.scss",
})
export class TextGroupComponent implements InputsWithSignals<TextGroup> {
  label = input<string>();
  value = input<string>();
  type = input<TextGroupType>("horizontal");
  labelWidth = input<string>("auto");

  classes = computed(() => {
    const classList = ["tedi-text-group"];
    if (this.type()) {
      classList.push(`tedi-text-group--${this.type()}`);
    }
    return classList.join(" ");
  });

  labelWidthStyle = computed(() => {
    if (this.labelWidth()) {
      return {
        "--label-width": this.labelWidth() ? this.labelWidth() : "auto",
      };
    } else return {};
  });
}

<dl [class]="classes()">
  <dt class="tedi-text-group__label" [style.--_label-width]="labelWidth()">
    <label>{{ label() }}</label>
  </dt>
  <dd class="tedi-text-group__value">{{ value() }}</dd>
</dl>

// libs/react-components/src/tedi/components/content/text-group/text-group.tsx
import cn from 'classnames';
import React from 'react';

import { BreakpointSupport, useBreakpointProps } from '../../../helpers';
import { Label } from '../label/label';
import styles from './text-group.module.scss';

type TextGroupType = 'vertical' | 'horizontal';

type TextGroupBreakpointProps = {
  /**
   * Type of text group layout
   */
  type?: TextGroupType;
  /**
   * Width for the label (e.g., '200px', '30%', etc.)
   * @default 'auto'
   */
  labelWidth?: string | number;
};

export interface TextGroupProps extends BreakpointSupport<TextGroupBreakpointProps> {
  /**
   * Label for the text group
   */
  label: string;
  /**
   * Value displayed alongside the label
   */
  value: React.ReactNode | React.ReactNode[];
  /**
   * Additional class name(s) to apply to the element
   */
  className?: string;
}

export const TextGroup = (props: TextGroupProps): JSX.Element => {
  const { getCurrentBreakpointProps } = useBreakpointProps();
  const {
    label,
    value,
    labelWidth = 'auto',
    className,
    type = 'vertical',
  } = getCurrentBreakpointProps<TextGroupProps>(props);

  const textGroupBEM = cn(styles['tedi-text-group'], styles[`tedi-text-group--${type}`], className);
  const labelWidthStyle = typeof labelWidth === 'number' ? `${labelWidth}%` : labelWidth;

  return (
    <dl className={textGroupBEM} style={{ '--label-width': labelWidthStyle }}>
      <dt className={cn(styles['tedi-text-group__label'])}>
        <Label>{label}</Label>
      </dt>
      <dd className={cn(styles['tedi-text-group__value'])}>{value}</dd>
    </dl>
  );
};
