// libs/angular-components/tedi/components/form/number-field/number-field.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
  ViewEncapsulation,
  forwardRef,
  ElementRef,
  signal,
  ViewChild,
} from "@angular/core";
import { ButtonComponent } from "../../buttons/button/button.component";
import { ComponentInputs } from "../../../types/inputs.type";
import { IconComponent } from "../../base/icon/icon.component";
import { TextComponent } from "../../base/text/text.component";
import { LabelComponent } from "../label/label.component";
import { FeedbackTextComponent } from "../feedback-text/feedback-text.component";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";

export type NumberFieldSize = "default" | "small";

@Component({
  selector: "tedi-number-field",
  standalone: true,
  templateUrl: "./number-field.component.html",
  styleUrl: "./number-field.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [
    LabelComponent,
    ButtonComponent,
    IconComponent,
    TextComponent,
    FeedbackTextComponent,
  ],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NumberFieldComponent),
      multi: true
    }
  ]
})
export class NumberFieldComponent implements ControlValueAccessor {
  /**
   * The unique identifier for the input element that this label is associated with. This ID should match the input element's id attribute to ensure accessibility.
   */
  id = input.required<string>();
  /**
   * The text content of the label that describes the input field.
   */
  label = input<string>();
  /**
   * Value of the input field. Supports two-way binding, use with form controls.
   */
  value = model<number>(0);
  /**
   * Is input disabled?
   * @default false
   */
  disabled = input<boolean>(false);
  /**
   * Indicates whether the input field is required. If set to true, the required indicator will be displayed next to the label.
   * @default false
   */
  required = input<boolean>(false);
  /**
   * Minimum allowed value. Disables decrementing below this value and restricts manual input.
   */
  min = input<number>();
  /**
   * Maximum allowed value. Disables incrementing above this value and restricts manual input.
   */
  max = input<number>();
  /**
   * Step size for incrementing or decrementing the value.
   * @default 1
   */
  step = input<number>(1);
  /**
   * Size of the number field.
   * @default default
   */
  size = input<NumberFieldSize>("default");
  /**
   * Marks the field as invalid for validation purposes.
   * @default false
   */
  invalid = input<boolean>(false);
  /**
   * Text displayed after the input value, typically a unit.
   */
  suffix = input<string>();
  /**
   * FeedbackText component inputs.
   */
  feedbackText = input<ComponentInputs<FeedbackTextComponent>>();

  @ViewChild('inputElement') inputRef!: ElementRef<HTMLInputElement>;
  
  private formDisabled = signal(false);
  private onChange: (value: number) => void = () => {};
  private onTouched: () => void = () => {};

  readonly isInvalid = computed(() => {
    const min = this.min();
    const max = this.max();

    return (
      this.invalid() ||
      Boolean(min !== undefined && this.value() < min) ||
      Boolean(max !== undefined && this.value() > max)
    );
  });

  readonly isDisabled = computed(() => this.disabled() || this.formDisabled());

  readonly decrementDisabled = computed(() => {
    const min = this.min();

    return this.isDisabled() || (min !== undefined && this.value() <= min);
  });

  readonly incrementDisabled = computed(() => {
    const max = this.max();

    return this.isDisabled() || (max !== undefined && this.value() >= max);
  });

  writeValue(value?: number): void {
    this.value.set(value ? (isNaN(value) ? 0 : value) : 0);
  }

  registerOnChange(fn: (value: number) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(disabled: boolean): void {
    this.formDisabled.set(disabled);
  }

  focus(): void {
    this.inputRef.nativeElement.focus();
  }

  blur(): void {
    this.inputRef.nativeElement.blur();
    this.onTouched();
  }

  handleButtonClick(action: "decrement" | "increment") {
    const delta = action === "decrement" ? -1 : 1;
    const nextValue = this.value() + this.step() * delta;
    this.value.set(nextValue);
    this.onChange(nextValue);
    this.onTouched();
  }

  handleInputChange(event: Event) {
    const input = event.target as HTMLInputElement;
    const value = isNaN(input.valueAsNumber) ? 0 : input.valueAsNumber;
    this.value.set(value);
    this.onChange(value);
  }

  handleBlur() {
    this.onTouched();
  }
}

@if (label()) {
  <label tedi-label [for]="id()" [required]="required()" [size]="size()">
    {{ label() }}
  </label>
}
<div
  [class]="{
    'tedi-number-field': true,
    'tedi-number-field--invalid': isInvalid(),
    'tedi-number-field--disabled': isDisabled(),
  }"
>
  <button
    tedi-button
    type="button"
    variant="secondary"
    [class]="{
      'tedi-number-field__button': true,
      'tedi-number-field__button--decrement': true,
      'tedi-number-field__button--small': size() === 'small',
    }"
    [disabled]="decrementDisabled()"
    (click)="handleButtonClick('decrement')"
  >
    <tedi-icon
      name="remove"
      [size]="18"
      [label]="'numberField.decrement' | tediTranslate: step()"
    />
  </button>
  <div
    [class]="{
      'tedi-number-field__input-wrapper': true,
      'tedi-number-field__input-wrapper--small': size() === 'small',
      'tedi-number-field__input-wrapper--disabled': isDisabled(),
      'tedi-number-field__input-wrapper--with-suffix': suffix(),
      'tedi-number-field__input-wrapper--full-width': fullWidth(),
    }"
    (click)="focus()"
  >
    <input
      #inputElement
      [id]="id()"
      type="number"
      inputmode="numeric"
      class="tedi-number-field__input"
      [value]="value()"
      [disabled]="isDisabled()"
      [required]="required()"
      [attr.min]="min()"
      [attr.max]="max()"
      [attr.step]="step()"
      [attr.aria-invalid]="isInvalid()"
      (input)="handleInputChange($event)"
      (blur)="handleBlur()"
    />
    @if (suffix()) {
      <small tedi-text color="tertiary" class="tedi-number-field__suffix">
        {{ suffix() }}
      </small>
    }
  </div>
  <button
    tedi-button
    type="button"
    variant="secondary"
    [class]="{
      'tedi-number-field__button': true,
      'tedi-number-field__button--increment': true,
      'tedi-number-field__button--small': size() === 'small',
    }"
    [disabled]="incrementDisabled()"
    (click)="handleButtonClick('increment')"
  >
    <tedi-icon
      name="add"
      [size]="18"
      [label]="'numberField.increment' | tediTranslate: step()"
    />
  </button>
</div>
@if (feedbackText(); as feedback) {
  <tedi-feedback-text
    [text]="feedback.text"
    [type]="feedback.type"
    [position]="feedback.position"
  />
}

// libs/react-components/src/tedi/components/form/number-field/number-field.tsx
import cn from 'classnames';
import React, { ChangeEvent, useCallback, useMemo, useRef, useState } from 'react';

import { BreakpointSupport, useBreakpointProps } from '../../../helpers';
import { useLabels } from '../../../providers/label-provider';
import { Text } from '../../base/typography/text/text';
import { Button } from '../../buttons/button/button';
import { FeedbackText, FeedbackTextProps } from '../feedback-text/feedback-text';
import { FormLabel, FormLabelProps } from '../form-label/form-label';
import styles from './number-field.module.scss';

type TDirection = 'increment' | 'decrement';

type NumberFieldBreakpointProps = {
  /**
   * Text displayed after the input value, typically a unit.
   */
  suffix?: string;
  /**
   * Whether the number field occupies the full width of its container.
   * @default false
   */
  fullWidth?: boolean;
  /**
   * Helper text displayed below the input.
   */
  helper?: FeedbackTextProps;
  /**
   * Step size for incrementing or decrementing the value.
   * @default 1
   */
  step?: number;
  /**
   * Additional attributes for the underlying input element.
   */
  input?: React.InputHTMLAttributes<HTMLInputElement>;
};

export interface NumberFieldProps extends BreakpointSupport<NumberFieldBreakpointProps>, FormLabelProps {
  /**
   * Initial value of the input field.
   */
  defaultValue?: number;
  /**
   * Controlled value of the input field. Overrides defaultValue.
   */
  value?: number;
  /**
   * Callback fired when the input value changes.
   */
  onChange?: (value: number) => void;
  /**
   * Specifies the input mode for the field (e.g., numeric or decimal).
   * @default numeric
   */
  inputMode?: 'numeric' | 'decimal';
  /**
   * Number of decimal places for rounding calculations.
   */
  decimalPlaces?: number;
  /**
   * Minimum allowed value. Disables decrementing below this value and restricts manual input.
   */
  min?: number;
  /**
   * Maximum allowed value. Disables incrementing above this value and restricts manual input.
   */
  max?: number;
  /**
   * Disables the input field.
   */
  disabled?: boolean;
  /**
   * Marks the field as invalid for validation purposes.
   */
  invalid?: boolean;
}

export const NumberField = (props: NumberFieldProps) => {
  const { getCurrentBreakpointProps } = useBreakpointProps(props.defaultServerBreakpoint);
  const {
    id,
    label,
    hideLabel,
    required,
    className,
    size,
    inputMode = 'numeric',
    decimalPlaces,
    min,
    max,
    step = 1,
    defaultValue,
    value,
    onChange,
    suffix,
    fullWidth = false,
    disabled = false,
    invalid = false,
    helper,
    input,
  } = getCurrentBreakpointProps<NumberFieldProps>(props);

  const { getLabel } = useLabels();

  const inputRef = useRef<HTMLInputElement>(null);

  const [inputUpdated, setInputUpdated] = useState<string>('');
  const [inputInnerValue, setInputInnerValue] = useState<number>(defaultValue ?? 0);

  const getCurrentValue = useMemo(
    (): number => (onChange && typeof value !== 'undefined' ? value : inputInnerValue),
    [onChange, value, inputInnerValue]
  );

  const helperId = helper ? helper?.id ?? `${id}-helper` : undefined;

  const isInvalid = useCallback(
    (currentValue: number): boolean => {
      const isBelowMinValue = Boolean(min !== undefined && currentValue < min);
      const isAboveMaxValue = Boolean(max !== undefined && currentValue > max);
      return invalid || isBelowMinValue || isAboveMaxValue || helper?.type === 'error';
    },
    [invalid, helper, max, min]
  );

  const forceToLimits = (currentValue: number) => {
    return Math.min(max ?? Infinity, Math.max(min ?? -Infinity, currentValue));
  };

  const updateValueUpdatedLabel = (newValue: number) => {
    const valueUpdated = getLabel('numberField.quantityUpdated', newValue);

    setInputUpdated(valueUpdated);
    setTimeout(() => {
      setInputUpdated('');
    }, 5000);
  };

  const roundValue = (currentValue: number) => {
    return decimalPlaces !== undefined ? parseFloat(currentValue.toFixed(decimalPlaces)) : currentValue;
  };

  const handleButtonClick = (direction: TDirection) => {
    let returnValue = getCurrentValue;

    if (direction === 'increment') {
      returnValue = returnValue + step;
    }
    if (direction === 'decrement') {
      returnValue = returnValue - step;
    }

    returnValue = forceToLimits(returnValue);
    returnValue = roundValue(returnValue);

    updateValueUpdatedLabel(returnValue);
    onChange?.(returnValue);
    setInputInnerValue(returnValue);
  };

  const handleInputChange = ({ currentTarget: { value } }: ChangeEvent<HTMLInputElement>) => {
    onChange?.(forceToLimits(+value));
    setInputInnerValue(forceToLimits(+value));
  };

  const renderButton = (direction: TDirection) => {
    const isOnOrOutOfBounds =
      direction === 'increment'
        ? max !== undefined && getCurrentValue >= max
        : min !== undefined && getCurrentValue <= min;

    const ButtonBEM = cn(styles['tedi-number-field__button'], styles[`tedi-number-field__button--${direction}`], {
      [styles['tedi-number-field__button--disabled']]: isOnOrOutOfBounds || disabled,
    });

    const changeValue = getLabel(`numberField.${direction}`, step);

    return (
      <Button
        aria-label={changeValue}
        onClick={() => handleButtonClick(direction)}
        disabled={isOnOrOutOfBounds || disabled}
        visualType="secondary"
        className={ButtonBEM}
        icon={{ name: direction === 'increment' ? 'add' : 'remove' }}
        size={size === 'small' ? 'small' : undefined}
      >
        {direction === 'increment' ? '+' : '-'}
      </Button>
    );
  };

  const renderInputElement = () => {
    const InputWrapperBEM = cn(styles['tedi-number-field__input-wrapper'], {
      [styles['tedi-number-field__input-wrapper--with-suffix']]: suffix,
      [styles['tedi-number-field__input-wrapper--full-width']]: fullWidth,
    });

    const InputBEM = cn(styles['tedi-number-field__input'], input?.className);
    const focusInput = () => inputRef?.current?.focus();

    return (
      <div className={InputWrapperBEM} onClick={focusInput}>
        <input
          ref={inputRef}
          id={id}
          aria-describedby={helperId}
          aria-invalid={invalid}
          type="number"
          inputMode={inputMode}
          value={getCurrentValue}
          min={min}
          max={max}
          required={required}
          step={step}
          disabled={disabled}
          onChange={handleInputChange}
          className={InputBEM}
          {...input}
        />
        {suffix && (
          <Text element="span" modifiers="small" color="tertiary" className={styles['tedi-number-field__suffix']}>
            {suffix}
          </Text>
        )}
      </div>
    );
  };

  const NumberFieldBem = cn(
    styles['tedi-number-field'],
    { [styles['tedi-number-field--invalid']]: isInvalid(getCurrentValue) },
    { [styles['tedi-number-field--disabled']]: disabled },
    { [styles['tedi-number-field--small']]: size === 'small' },
    className
  );

  return (
    <div data-name="number-field" className={className}>
      <FormLabel id={id} label={label} required={required} hideLabel={hideLabel} size={size} />
      <div className={NumberFieldBem}>
        {renderButton('decrement')}
        {renderInputElement()}
        {renderButton('increment')}
      </div>
      {helper && <FeedbackText {...helper} id={helperId} />}
      <div aria-live="polite" className="visually-hidden">
        {inputUpdated}
      </div>
    </div>
  );
};

NumberField.displayName = 'NumberField';

export default NumberField;
