// libs/react-components/tedi/src/components/spinner/spinner.tsx
import cn from 'classnames';

import styles from './spinner.module.scss';

export type SpinnerSize = 10 | 16 | 48;
export type SpinnerColor = 'primary' | 'secondary';
export type SpinnerPosition = 'absolute';

export interface SpinnerProps {
  /**
   * Additional class name
   */
  className?: string;
  /**
   * Size of the spinner
   * @default 16
   */
  size?: SpinnerSize;
  /**
   * Which color spinner should be
   * @default 'primary'
   */
  color?: SpinnerColor;
  /**
   * Label for screen-readers
   * If omitted then the spinner is hidden for screen-readers
   */
  label?: string;
  /**
   * Position of the spinner
   */
  position?: SpinnerPosition;
}

export const Spinner = (props: SpinnerProps): JSX.Element => {
  const { className, size = 16, color = 'primary', label = props.label, position } = props;

  const spinnerBEM = cn(
    styles['tedi-spinner'],
    className,
    position && styles[`tedi-spinner--${position}`],
    size && styles[`tedi-spinner--size-${size}`],
    color && styles[`tedi-spinner--color-${color}`]
  );

  return (
    <span className={spinnerBEM} role="status" aria-live="polite" aria-label={label}>
      <svg viewBox="22 22 44 44" aria-hidden="true">
        <circle className={styles['tedi-spinner--inner']} cx="44" cy="44" r="20" fill="none"></circle>
      </svg>
    </span>
  );
};

// libs/angular-components/src/tedi/components/spinner/spinner.component.ts
import { Component, Input } from '@angular/core';

type SpinnerSize = 10 | 16 | 18 | 48;
type SpinnerColor = 'primary' | 'secondary';
type SpinnerPosition = 'absolute';

export interface SpinnerProps {
  /**
   * Defines the size of the spinner. Accepted values: 10 (small), 16 (default), 48 (large).
   * @default 16
   */
  size?: SpinnerSize;
  color?: SpinnerColor;
  position?: SpinnerPosition;
  className?: string;
  label?: string;
}

@Component({
  selector: 'app-spinner',
  templateUrl: './spinner.component.html',
  styleUrls: ['./spinner.component.scss'],
})
export class SpinnerComponent implements SpinnerProps {
  @Input() size: SpinnerSize = 16;
  @Input() color: SpinnerColor = 'primary';
  @Input() position?: SpinnerPosition;
  @Input() className?: string;
  @Input() label: string = 'Loading...';

  get spinnerClasses(): string {
    const classes = ['tedi-spinner'];
    if (this.className) classes.push(this.className);
    if (this.position) classes.push(`tedi-spinner--${this.position}`);
    classes.push(`tedi-spinner--size-${this.size}`);
    classes.push(`tedi-spinner--color-${this.color}`);
    return classes.join(' ');
  }
}

<span [class]="spinnerClasses" role="status" aria-live="polite" [attr.aria-label]="label" [attr.aria-hidden]="!label">
  <svg viewBox="22 22 44 44" aria-hidden="true">
    <circle class="tedi-spinner--inner" cx="44" cy="44" r="20" fill="none"></circle>
  </svg>
</span>
